name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.6"]
        ghc: ["8.10.1", "8.10.2", "8.10.3", "8.10.4", "8.10.5", "8.10.6", "8.10.7"]

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # GitHub preinstalls recent GHC versions, and haskell/actions/setup uses the
    # preinstalled version when possible. However, GitHub's preinstalled GHC does
    # not include documentation, and we need documentation to run Haddock tests.
    # Therefore, we reinstall GHC to ensure that we have the documentation we
    # need.

    # TODO: Only reinstall GHC when the docs are actually missing. (If we're
    # using a GHC version that is not preinstalled by GitHub, then we will be
    # using a GHC installed by ghcup, which should have documentation.)
    - name: Reinstall GHC with docs
      run: |
        ghcup rm ghc ${{ matrix.ghc }}
        ghcup install ghc ${{ matrix.ghc }}

    - name: Freeze
      run: |
        cabal freeze
 
    - uses: actions/cache@v2
      name: Cache ~/.cabal/store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Build
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=streaming
        cabal build all

    - name: Make test output directory
      id: make-test-output-dir
      run: |
        mkdir -p ${{ github.workspace }}/test-output

    - name: Test
      run: cabal test all --test-log='${{ github.workspace }}/test-output/$pkgid-$compiler-$os-$arch-$test-suite-$result.txt'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      if: always() && steps.make-test-output-dir.conclusion == 'success'
      with:
        name: test-output
        path: ${{ github.workspace }}/test-output/

